CREATE DATABASE IF NOT EXISTS homedb;

GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' IDENTIFIED BY 'homepwd' WITH GRANT OPTION;

DROP TABLE IF EXISTS users;

CREATE TABLE users(id INT PRIMARY KEY AUTO_INCREMENT, username VARCHAR(59), PASSWORD VARCHAR(59), email VARCHAR(50));